#version 450

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, std430) readonly buffer InputBuffer {
    uint data[];
} input_buffer;

layout(set = 0, binding = 1, std430) writeonly buffer OutputBuffer {
    uint data[];
} output_buffer;

layout(push_constant) uniform PushConstants {
    uint word_count;
} push_constants;

void main()
{
    uint word_index = gl_GlobalInvocationID.x;

    if (word_index < push_constants.word_count)
        output_buffer.data[word_index] = input_buffer.data[word_index];
}
