#version 450

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform sampler2D rendered_image;
layout(set = 0, binding = 1, std430) writeonly buffer OutputPixels {
    uint pixels[];
} output_pixels;

void main()
{
    uvec2 pixel = gl_GlobalInvocationID.xy;
    uint index = pixel.y * 64u + pixel.x;
    vec4 color = texelFetch(rendered_image, ivec2(pixel), 0);
    output_pixels.pixels[index] = packUnorm4x8(color);
}
